Document: evepac
Title: Debian evepac Manual
Author: <insert document author here>
Abstract: This manual describes what evepac is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/evepac/evepac.sgml.gz

Format: postscript
Files: /usr/share/doc/evepac/evepac.ps.gz

Format: text
Files: /usr/share/doc/evepac/evepac.text.gz

Format: HTML
Index: /usr/share/doc/evepac/html/index.html
Files: /usr/share/doc/evepac/html/*.html
